    type Query {
        files(path:String! token:String!): [File]
        file(path:String! token:String!): File
    }

    type File {
        # _id: ID!,
        path: String!,
        type: String,
        # creationDate: Int,
        size: Int
    }

    input NewFile {
        type: String,
        size: Int!,
        creationDate: Int
    }

    type Mutation {
        addFile(new: NewFile!): Boolean!
    }