scalar Upload

  type UpFile {
    id: ID!
    path: String!
    filename: String!
    mimetype: String!
    encoding: String!
  }

type Query {
    uploads: [UpFile]
}

type Mutation {
    singleUpload (file: Upload!): UpFile!
}